name = "smyst-translate"
main = "workers/translate.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "186363805f9fc571fd16528a1ed7c52d"

routes = [
  { pattern = "smyst.com/*", zone_name = "smyst.com" },
]

[vars]
ORIGIN_URL = "https://smyst-app-67m.pages.dev"
CANONICAL_HOST = "https://smyst.com"

[[kv_namespaces]]
binding = "TRANSLATIONS"
id = "9790a73572ff4308aed92cb45879f81e"
